// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-NfNypy2LD-Wch0m_QAG3CNjenNLaW4',
    appId: '1:1044913677198:web:3945ce86905e9bf13e7adf',
    messagingSenderId: '1044913677198',
    projectId: 'chat-app-fire-b5c4c',
    authDomain: 'chat-app-fire-b5c4c.firebaseapp.com',
    storageBucket: 'chat-app-fire-b5c4c.firebasestorage.app',
    measurementId: 'G-6YFEH27HZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSe6O3-bv9lK05r7MIctnMdb6NEqGKRw',
    appId: '1:1044913677198:android:d303c3423dcfaea43e7adf',
    messagingSenderId: '1044913677198',
    projectId: 'chat-app-fire-b5c4c',
    storageBucket: 'chat-app-fire-b5c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwEeD3oYM-1jZr-8yj00yiryy_4J6zbtQ',
    appId: '1:1044913677198:ios:1c2311c186c2dc233e7adf',
    messagingSenderId: '1044913677198',
    projectId: 'chat-app-fire-b5c4c',
    storageBucket: 'chat-app-fire-b5c4c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwEeD3oYM-1jZr-8yj00yiryy_4J6zbtQ',
    appId: '1:1044913677198:ios:1c2311c186c2dc233e7adf',
    messagingSenderId: '1044913677198',
    projectId: 'chat-app-fire-b5c4c',
    storageBucket: 'chat-app-fire-b5c4c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-NfNypy2LD-Wch0m_QAG3CNjenNLaW4',
    appId: '1:1044913677198:web:b86b38ca44c3ca1d3e7adf',
    messagingSenderId: '1044913677198',
    projectId: 'chat-app-fire-b5c4c',
    authDomain: 'chat-app-fire-b5c4c.firebaseapp.com',
    storageBucket: 'chat-app-fire-b5c4c.firebasestorage.app',
    measurementId: 'G-SXP41KBHV0',
  );
}
